# Generated by Django 5.1.7 on 2025-04-02 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(default='0000', max_length=10, unique=True)),
                ('start_location', models.CharField(default='Unknown', max_length=255)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination', models.CharField(default='Unknown', max_length=255)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('miles_driving_today', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_mileage_today', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('carrier_name', models.CharField(default='Unknown', max_length=255)),
                ('main_office_address', models.TextField(default='Unknown')),
                ('home_terminal_address', models.TextField(default='Unknown')),
                ('truck_trailer_info', models.TextField(default='Unknown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duty_status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trips.trip')),
            ],
        ),
    ]
