# Generated by Django 5.1.7 on 2025-03-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_current_cycle_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='miles_driving_today',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_mileage_today',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
