# Generated by Django 5.1.7 on 2025-03-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_miles_driving_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(default='0000', max_length=4, unique=True),
        ),
    ]
