# Generated by Django 5.1.7 on 2025-03-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(default='0000', max_length=10, unique=True),
        ),
    ]
